<a href="https://colab.research.google.com/github/vodnalashiva131/INFO-5731/blob/main/vodnala_shiva_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Students are expected to complete the exercise during lecture period to meet the active participation criteria of the course.
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of the day tomorrow, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**


## Question 1 (10 Points)
Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

It looks as if you've supplied a complete assessment of diverse functions that can be used for sentiment analysis of product reviews. here's a breakdown of the way every feature contributes to sentiment analysis:

Bag-of-Words: BoW representation captures the presence and frequency of phrases in evaluations. it's a easy but powerful way to symbolize textual content facts, allowing models to analyze from the incidence of phrases associated with tremendous, negative, or neutral sentiments.

TF-IDF: TF-IDF allows to downweight the importance of words which can be not unusual across files however less informative approximately sentiment. it is able to assist distinguish between phrases which can be common however no longer always indicative of sentiment.

N-grams: N-grams capture contextual data by way of considering sequences of words in preference to individual words. This lets in fashions to learn from terms or expressions that bring sentiment extra successfully, which include "no longer exact" or "very glad."

Sentiment Lexicons: Sentiment lexicons provide lists of phrases with their related sentiment polarity. through incorporating those lexicons, fashions can extract features indicating the presence of sentiment-bearing words, which enables in accurately classifying reviews primarily based on sentiment.

Part-of-Speech Tags: POS tagging allows capture syntactic systems and grammatical styles that make contributions to sentiment. via identifying adjectives, adverbs, and different parts of speech that frequently carry sentiment facts, models can higher recognize the sentiment expressed in critiques.

Every of these features gives unique insights into the sentiment of product critiques, and combining them can provide a richer illustration of the text statistics, leading to extra correct sentiment type. system mastering models like SVM, Naive Bayes, or neural networks can leverage these capabilities to efficaciously classify critiques into tremendous, poor, or impartial classes. Experimenting with unique combos of features and fashions can in addition beautify the accuracy of sentiment analysis for product opinions.

'''

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [ ]:
import sys
!{sys.executable} -m pip install nltk

import nltk
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.util import ngrams
from nltk.sentiment.util import mark_negation
from nltk import pos_tag
from nltk.corpus import opinion_lexicon

comments = [
    "This product is great! It exceeded my expectations.",
    "The product quality is poor and disappointing.",
    "I am satisfied with the performance of this product.",
    "Not a good experience. I would not recommend it.",
    "The customer service was excellent.",
    "The delivery was late and the packaging was damaged."
]


bow_vectorizer = CountVectorizer()
bow_features = bow_vectorizer.fit_transform(comments)
print("Bag-of-Words Features:")
print(bow_features.toarray())
print(bow_vectorizer.get_feature_names_out())
print()


Bag-of-Words Features:
[[0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0]
 [0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 2 0 2 0 0]]
['am' 'and' 'customer' 'damaged' 'delivery' 'disappointing' 'exceeded'
 'excellent' 'expectations' 'experience' 'good' 'great' 'is' 'it' 'late'
 'my' 'not' 'of' 'packaging' 'performance' 'poor' 'product' 'quality'
 'recommend' 'satisfied' 'service' 'the' 'this' 'was' 'with' 'would']



In [ ]:
tfidf = TfidfVectorizer()
tfidf_features = tfidf.fit_transform(comments)
print("TF-IDF Features:")
print(tfidf_features.toarray())
print(tfidf.get_feature_names_out())
print()

TF-IDF Features:
[[0.         0.         0.         0.         0.         0.
  0.39233589 0.         0.39233589 0.         0.         0.39233589
  0.32172105 0.32172105 0.         0.39233589 0.         0.
  0.         0.         0.         0.27161901 0.         0.
  0.         0.         0.         0.32172105 0.         0.
  0.        ]
 [0.         0.36042932 0.         0.         0.         0.43954028
  0.         0.         0.         0.         0.         0.
  0.36042932 0.         0.         0.         0.         0.
  0.         0.         0.43954028 0.30429919 0.43954028 0.
  0.         0.         0.26076129 0.         0.         0.
  0.        ]
 [0.3921214  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.3921214
  0.         0.3921214  0.         0.27147051 0.         0.
  0.3921214  0.         0.2326296  0.32154515 0.         0.3921214
  0.        ]
 [0.       

In [ ]:
import nltk
nltk.download('punkt')
n = 2
ngram_features = []
for comment in comments:
    tokens = word_tokenize(comment)
    bigrams = list(ngrams(tokens, n))
    ngram_features.append(bigrams)
print("N-gram Features:")
print(ngram_features)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


N-gram Features:
[[('This', 'product'), ('product', 'is'), ('is', 'great'), ('great', '!'), ('!', 'It'), ('It', 'exceeded'), ('exceeded', 'my'), ('my', 'expectations'), ('expectations', '.')], [('The', 'product'), ('product', 'quality'), ('quality', 'is'), ('is', 'poor'), ('poor', 'and'), ('and', 'disappointing'), ('disappointing', '.')], [('I', 'am'), ('am', 'satisfied'), ('satisfied', 'with'), ('with', 'the'), ('the', 'performance'), ('performance', 'of'), ('of', 'this'), ('this', 'product'), ('product', '.')], [('Not', 'a'), ('a', 'good'), ('good', 'experience'), ('experience', '.'), ('.', 'I'), ('I', 'would'), ('would', 'not'), ('not', 'recommend'), ('recommend', 'it'), ('it', '.')], [('The', 'customer'), ('customer', 'service'), ('service', 'was'), ('was', 'excellent'), ('excellent', '.')], [('The', 'delivery'), ('delivery', 'was'), ('was', 'late'), ('late', 'and'), ('and', 'the'), ('the', 'packaging'), ('packaging', 'was'), ('was', 'damaged'), ('damaged', '.')]]


In [ ]:
import nltk
nltk.download('punkt')


sentiment_lexicon = opinion_lexicon.words()
sentiment_features = []
for comment in comments:
    tokens = word_tokenize(comment.lower())
    sentiment_words = [word for word in tokens if word in sentiment_lexicon]
    sentiment_features.append(sentiment_words)
print("Sentiment Lexicon Features:")
print(sentiment_features)
print()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Sentiment Lexicon Features:
[['great', 'exceeded'], ['poor', 'disappointing'], ['satisfied'], ['good', 'recommend'], ['excellent'], ['damaged']]



In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')

pos_features = []
for revcommentiew in comments:
    tokens = word_tokenize(comment)
    pos_tags = pos_tag(tokens)
    pos_features.append(pos_tags)
print("POS Features:")
print(pos_features)
print()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


POS Features:
[[('This', 'DT'), ('product', 'NN'), ('is', 'VBZ'), ('great', 'JJ'), ('!', '.'), ('It', 'PRP'), ('exceeded', 'VBD'), ('my', 'PRP$'), ('expectations', 'NNS'), ('.', '.')], [('The', 'DT'), ('product', 'NN'), ('quality', 'NN'), ('is', 'VBZ'), ('poor', 'JJ'), ('and', 'CC'), ('disappointing', 'JJ'), ('.', '.')], [('I', 'PRP'), ('am', 'VBP'), ('satisfied', 'JJ'), ('with', 'IN'), ('the', 'DT'), ('performance', 'NN'), ('of', 'IN'), ('this', 'DT'), ('product', 'NN'), ('.', '.')], [('Not', 'RB'), ('a', 'DT'), ('good', 'JJ'), ('experience', 'NN'), ('.', '.'), ('I', 'PRP'), ('would', 'MD'), ('not', 'RB'), ('recommend', 'VB'), ('it', 'PRP'), ('.', '.')], [('The', 'DT'), ('customer', 'NN'), ('service', 'NN'), ('was', 'VBD'), ('excellent', 'JJ'), ('.', '.')], [('The', 'DT'), ('delivery', 'NN'), ('was', 'VBD'), ('late', 'JJ'), ('and', 'CC'), ('the', 'DT'), ('packaging', 'NN'), ('was', 'VBD'), ('damaged', 'VBN'), ('.', '.')]]



## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [ ]:
from sklearn.feature_selection import mutual_info_classif

all_features = bow_features.toarray()
labels = [1, 0, 1, 0, 1, 0]
matched_information = matched_information_classif(all_features, labels)
feature_importance = list(zip(bow_vectorizer.get_feature_names_out(), matched_information))
sorted_features = sorted(feature_importance, key=lambda x: x[1], reverse=True)
print("Ranked Features based on Mutual Information:")
for feature, importance in sorted_features:
    print(f"Feature: {feature}, Importance: {importance}")


Ranked Features based on Mutual Information:
Feature: and, Importance: 0.5194444444444445
Feature: experience, Importance: 0.3388888888888889
Feature: of, Importance: 0.2416666666666667
Feature: poor, Importance: 0.2416666666666667
Feature: packaging, Importance: 0.19999999999999996
Feature: this, Importance: 0.18611111111111112
Feature: great, Importance: 0.15833333333333344
Feature: expectations, Importance: 0.07499999999999996
Feature: quality, Importance: 0.07499999999999996
Feature: recommend, Importance: 0.03333333333333344
Feature: satisfied, Importance: 0.019444444444444597
Feature: am, Importance: 0.0
Feature: customer, Importance: 0.0
Feature: damaged, Importance: 0.0
Feature: delivery, Importance: 0.0
Feature: disappointing, Importance: 0.0
Feature: exceeded, Importance: 0.0
Feature: excellent, Importance: 0.0
Feature: good, Importance: 0.0
Feature: is, Importance: 0.0
Feature: it, Importance: 0.0
Feature: late, Importance: 0.0
Feature: my, Importance: 0.0
Feature: not, Impo

## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [ ]:
!pip install sentence-transformers

import numpy as np
import torch
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

comments = [
    "This product is great! It exceeded my expectations.",
    "The product quality is poor and disappointing.",
    "I am satisfied with the performance of this product.",
    "Not a good experience. I would not recommend it.",
    "The customer service was excellent.",
    "The delivery was late and the packaging was damaged."
]

query = "I want to buy a product with excellent quality and good customer service."

model = SentenceTransformer('bert-base-nli-mean-tokens')

q_embedded = model.encode(query, convert_to_tensor=True)
reviewed_embiddings = model.encode(comments, convert_to_tensor=True)
q_embeddeds = q_embedded.reshape(1, -1)
reviewed_embiddings = reviewed_embiddings.reshape(len(comments), -1)
similarities = cosine_similarity(q_embedded, reviewed_embiddings)
ranked_indexes = np.argsort(similarities[0])[::-1]
print("Ranked Text Documents based on Similarity to Query:")
for idx in ranked_indexes:
    print(f"Similarity: {similarities[0][idx]}, Review: {comments[idx]}")


Ranked Text Documents based on Similarity to Query:
Similarity: 0.8104807138442993, Review: I am satisfied with the performance of this product.
Similarity: 0.8018361330032349, Review: The customer service was excellent.
Similarity: 0.7438066005706787, Review: This product is great! It exceeded my expectations.
Similarity: 0.26841312646865845, Review: The product quality is poor and disappointing.
Similarity: 0.24808931350708008, Review: The delivery was late and the packaging was damaged.
Similarity: 0.24685847759246826, Review: Not a good experience. I would not recommend it.


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

**Learning Experience:**
Overall, working on extracting functions from textual content information become a precious studying enjoy. It supplied a realistic know-how of various strategies used in natural language processing (NLP) for feature extraction. the key standards i found most beneficial had been Bag-of-phrases (BoW), TF-IDF, N-grams, and function choice methods like mutual information. know-how how to constitute textual content data in a format appropriate for gadget mastering models is vital in NLP tasks, and this exercise helped support the ones ideas.

**Challenges Encountered:**
One task I encountered turned into setting up the surroundings and putting in the important libraries. additionally, knowledge the intricacies of characteristic choice techniques and making sure the proper preprocessing of text facts required some attempt. but, with the assist of documentation and on-line sources, i was capable to conquer these demanding situations.

**Relevance to Your Field of Study:**
This workout is enormously applicable to the sphere of NLP. function extraction is a essential step in text processing obligations such as sentiment analysis, text type, and records retrieval. by means of studying a way to extract and choose features from text facts, I gained insights into the preprocessing steps necessary for building powerful NLP models. This know-how is essential for everybody working in the subject of NLP, as it bureaucracy the muse for greater advanced strategies and algorithms.


